### ISSUE TITLE
cos\theta should be flat, dN/d\theta ~ sin\theta

### ISSUE THREAD

**Issue by mmikhasenko** [ComPWA/compwa.github.io#268]
The distribution over the angle does not look as expected.

![image](https://github.com/ComPWA/compwa.github.io/assets/22725744/6800c607-d793-46ef-b03d-45d1733ba961)

Can it be because of the boost to wrong direction? `beta-> -beta`

![image](https://github.com/ComPWA/compwa.github.io/assets/22725744/ca519c53-f28a-4d35-a24e-da5a71424566)

**Comment by shenvitor** [comment]
Thanks for noting! It is to be fixed in https://github.com/ComPWA/compwa.github.io/pull/217.

**Comment by shenvitor** [comment]
![image](https://github.com/ComPWA/compwa.github.io/assets/17490173/15bd748d-c587-418f-bcf3-17dcdd2c099f)
Now we can see the modulation!
